# Generated by Django 2.2.5 on 2019-09-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilldetails',
            old_name='client_id',
            new_name='medication_name',
        ),
        migrations.RenameField(
            model_name='pilldetails',
            old_name='mg_dose',
            new_name='num_mg',
        ),
        migrations.RenameField(
            model_name='pilldetails',
            old_name='medicine_name',
            new_name='pills_per_dose',
        ),
        migrations.RemoveField(
            model_name='pilldetails',
            name='pill_per_dose',
        ),
    ]
